// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Account
{
    public string AccountId { get; set; }

    public string Role { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public virtual ICollection<BatteryReport> BatteryReports { get; set; } = new List<BatteryReport>();

    public virtual ICollection<BssStaff> BssStaffs { get; set; } = new List<BssStaff>();

    public virtual ICollection<Evdriver> Evdrivers { get; set; } = new List<Evdriver>();

    public virtual ICollection<ExchangeBattery> ExchangeBatteries { get; set; } = new List<ExchangeBattery>();

    public virtual ICollection<Form> Forms { get; set; } = new List<Form>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();
}