// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Battery
{
    public string BatteryId { get; set; }

    public string Status { get; set; }

    public decimal? Capacity { get; set; }

    public string BatteryType { get; set; }

    public string StationId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<BatteryHistory> BatteryHistories { get; set; } = new List<BatteryHistory>();

    public virtual ICollection<BatteryReport> BatteryReports { get; set; } = new List<BatteryReport>();

    public virtual ICollection<ExchangeBattery> ExchangeBatteryNewBatteries { get; set; } = new List<ExchangeBattery>();

    public virtual ICollection<ExchangeBattery> ExchangeBatteryOldBatteries { get; set; } = new List<ExchangeBattery>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Package> Packages { get; set; } = new List<Package>();

    public virtual ICollection<Slot> Slots { get; set; } = new List<Slot>();

    public virtual Station Station { get; set; }

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}