// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class BatteryReport
{
    public string BatteryReportId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public string AccountId { get; set; }

    public string StationId { get; set; }

    public string BatteryId { get; set; }

    public string Status { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Account Account { get; set; }

    public virtual Battery Battery { get; set; }

    public virtual Station Station { get; set; }
}