// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class BatteryHistory
{
    public string BatteryHistoryId { get; set; }

    public string BatteryId { get; set; }

    public string ExchangeBatteryId { get; set; }

    public string Vin { get; set; }

    public string StationId { get; set; }

    public string ActionType { get; set; }

    public string EnergyLevel { get; set; }

    public DateTime? ActionDate { get; set; }

    public string Notes { get; set; }

    public string Status { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Battery Battery { get; set; }

    public virtual ExchangeBattery ExchangeBattery { get; set; }

    public virtual Station Station { get; set; }

    public virtual Vehicle VinNavigation { get; set; }
}