// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class BssStaff
{
    public string StaffId { get; set; }

    public string AccountId { get; set; }

    public string StationId { get; set; }

    public virtual Account Account { get; set; }

    public virtual Station Station { get; set; }
}