// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Evdriver
{
    public string CustomerId { get; set; }

    public string Vin { get; set; }

    public string AccountId { get; set; }

    public virtual Account Account { get; set; }

    public virtual Vehicle VinNavigation { get; set; }
}