// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BusinessObjects.Models;

public partial class ExchangeBattery
{
    public string ExchangeBatteryId { get; set; }

    public string Vin { get; set; }

    public string OldBatteryId { get; set; }

    public string NewBatteryId { get; set; }

    public string StaffAccountId { get; set; }

    public string ScheduleId { get; set; }

    public string OrderId { get; set; }

    public string StationId { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<BatteryHistory> BatteryHistories { get; set; } = new List<BatteryHistory>();

    public virtual ICollection<BatteryReport> BatteryReports { get; set; } = new List<BatteryReport>();
    [JsonIgnore]
    public virtual Battery NewBattery { get; set; }
    [JsonIgnore]
    public virtual Battery OldBattery { get; set; }
    [JsonIgnore]
    public virtual Order Order { get; set; }
    [JsonIgnore]
    public virtual StationSchedule Schedule { get; set; }
    [JsonIgnore]
    public virtual Account StaffAccount { get; set; }
    [JsonIgnore]
    public virtual Station Station { get; set; }
    [JsonIgnore]
    public virtual Vehicle VinNavigation { get; set; }
}