// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BusinessObjects.Models;

public partial class Form
{
    public string FormId { get; set; }

    public string AccountId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime? Date { get; set; }

    public string StationId { get; set; }

    public string Status { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string Vin { get; set; }

    public string BatteryId { get; set; }
    [JsonIgnore]
    public virtual Account Account { get; set; }
    [JsonIgnore]
    public virtual Station Station { get; set; }

    public virtual ICollection<StationSchedule> StationSchedules { get; set; } = new List<StationSchedule>();
}