// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Order
{
    public string OrderId { get; set; }

    public string AccountId { get; set; }

    public double? Total { get; set; }

    public string BatteryId { get; set; }

    public DateTime? Date { get; set; }

    public string ServiceId { get; set; }

    public virtual Account Account { get; set; }

    public virtual Battery Battery { get; set; }

    public virtual ICollection<ExchangeBattery> ExchangeBatteries { get; set; } = new List<ExchangeBattery>();
}