// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Package
{
    public string PackageId { get; set; }

    public string BatteryId { get; set; }

    public double? Price { get; set; }

    public string Description { get; set; }

    public virtual Battery Battery { get; set; }

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}