// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Package
{
    public string PackageId { get; set; }

    public decimal? Price { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string PackageName { get; set; }

    public string BatteryType { get; set; }

    public DateTime? ExpiredDate { get; set; }

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}