// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BusinessObjects.Models;

public partial class Rating
{
    public string RatingId { get; set; }

    public decimal? Rating1 { get; set; }

    public string Description { get; set; }

    public string StationId { get; set; }

    public string AccountId { get; set; }

    public string Status { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string Image { get; set; }
    [JsonIgnore]
    public virtual Account Account { get; set; }
    [JsonIgnore]
    public virtual Station Station { get; set; }
}