// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Slot
{
    public string SlotId { get; set; }

    public string StationId { get; set; }

    public string Status { get; set; }

    public string BatteryId { get; set; }

    public int? CordinateX { get; set; }

    public int? CordinateY { get; set; }

    public virtual Battery Battery { get; set; }

    public virtual Station Station { get; set; }
}