// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Station
{
    public string StationId { get; set; }

    public int? BatteryNumber { get; set; }

    public string Location { get; set; }

    public string Status { get; set; }

    public decimal? Rating { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string StationName { get; set; }

    public string Image { get; set; }

    public virtual ICollection<Battery> Batteries { get; set; } = new List<Battery>();

    public virtual ICollection<BatteryHistory> BatteryHistories { get; set; } = new List<BatteryHistory>();

    public virtual ICollection<BatteryReport> BatteryReports { get; set; } = new List<BatteryReport>();

    public virtual ICollection<BssStaff> BssStaffs { get; set; } = new List<BssStaff>();

    public virtual ICollection<ExchangeBattery> ExchangeBatteries { get; set; } = new List<ExchangeBattery>();

    public virtual ICollection<Form> Forms { get; set; } = new List<Form>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<Slot> Slots { get; set; } = new List<Slot>();

    public virtual ICollection<StationSchedule> StationSchedules { get; set; } = new List<StationSchedule>();
}