// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BusinessObjects.Models;

public partial class StationSchedule
{
    public string StationScheduleId { get; set; }

    public DateTime? Date { get; set; }

    public string Description { get; set; }

    public string StationId { get; set; }

    public string FormId { get; set; }

    public string Status { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<ExchangeBattery> ExchangeBatteries { get; set; } = new List<ExchangeBattery>();
    [JsonIgnore]
    public virtual Form Form { get; set; }
    [JsonIgnore]
    public virtual Station Station { get; set; }
}