// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BusinessObjects.Models;

public partial class SwapXContext : DbContext
{
    public SwapXContext(DbContextOptions<SwapXContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Battery> Batteries { get; set; }

    public virtual DbSet<BatteryHistory> BatteryHistories { get; set; }

    public virtual DbSet<BatteryReport> BatteryReports { get; set; }

    public virtual DbSet<BssStaff> BssStaffs { get; set; }

    public virtual DbSet<Evdriver> Evdrivers { get; set; }

    public virtual DbSet<ExchangeBattery> ExchangeBatteries { get; set; }

    public virtual DbSet<Form> Forms { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Package> Packages { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<Slot> Slots { get; set; }

    public virtual DbSet<Station> Stations { get; set; }

    public virtual DbSet<StationSchedule> StationSchedules { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__Account__F267253EF7CE81BF");

            entity.ToTable("Account");

            entity.Property(e => e.AccountId)
                .HasMaxLength(50)
                .HasColumnName("accountID");
            entity.Property(e => e.Address)
                .HasMaxLength(50)
                .HasColumnName("address");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .HasColumnName("email");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .HasMaxLength(50)
                .HasColumnName("password");
            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .HasColumnName("phone");
            entity.Property(e => e.Role)
                .HasMaxLength(50)
                .HasDefaultValue("EV Driver");
            entity.Property(e => e.Username)
                .HasMaxLength(50)
                .HasColumnName("username");
        });

        modelBuilder.Entity<Battery>(entity =>
        {
            entity.HasKey(e => e.BatteryId).HasName("PK__Battery__5710803E6F683227");

            entity.ToTable("Battery");

            entity.Property(e => e.BatteryId)
                .HasMaxLength(50)
                .HasColumnName("BatteryID");
            entity.Property(e => e.BatteryType)
                .HasMaxLength(25)
                .HasColumnName("Battery_type");
            entity.Property(e => e.Capacity).HasColumnName("capacity");
            entity.Property(e => e.StationId)
                .HasMaxLength(50)
                .HasColumnName("stationID");
            entity.Property(e => e.Status).HasMaxLength(25);

            entity.HasOne(d => d.Station).WithMany(p => p.Batteries)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK__Battery__station__571DF1D5");
        });

        modelBuilder.Entity<BatteryHistory>(entity =>
        {
            entity.HasKey(e => e.BatteryHistory1).HasName("PK__BatteryH__98B8C9501C954EE1");

            entity.ToTable("BatteryHistory");

            entity.Property(e => e.BatteryHistory1)
                .HasMaxLength(50)
                .HasColumnName("BatteryHistory");
            entity.Property(e => e.ActionType).HasMaxLength(50);
            entity.Property(e => e.BatteryId)
                .HasMaxLength(50)
                .HasColumnName("BatteryID");
            entity.Property(e => e.EnergyLevel).HasMaxLength(50);
            entity.Property(e => e.ExchangeBatteryId)
                .HasMaxLength(50)
                .HasColumnName("ExchangeBatteryID");
            entity.Property(e => e.Notes).HasMaxLength(50);
            entity.Property(e => e.StationId)
                .HasMaxLength(50)
                .HasColumnName("stationID");
            entity.Property(e => e.Vin)
                .HasMaxLength(25)
                .HasColumnName("VIN");

            entity.HasOne(d => d.Battery).WithMany(p => p.BatteryHistories)
                .HasForeignKey(d => d.BatteryId)
                .HasConstraintName("FK__BatteryHi__Batte__5812160E");

            entity.HasOne(d => d.ExchangeBattery).WithMany(p => p.BatteryHistories)
                .HasForeignKey(d => d.ExchangeBatteryId)
                .HasConstraintName("FK__BatteryHi__Excha__59063A47");

            entity.HasOne(d => d.Station).WithMany(p => p.BatteryHistories)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK__BatteryHi__stati__59FA5E80");

            entity.HasOne(d => d.VinNavigation).WithMany(p => p.BatteryHistories)
                .HasForeignKey(d => d.Vin)
                .HasConstraintName("FK__BatteryHist__VIN__5AEE82B9");
        });

        modelBuilder.Entity<BatteryReport>(entity =>
        {
            entity.HasKey(e => e.BatteryReportId).HasName("PK__BatteryR__0A361DA777618EA6");

            entity.ToTable("BatteryReport");

            entity.Property(e => e.BatteryReportId)
                .HasMaxLength(50)
                .HasColumnName("BatteryReportID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(50)
                .HasColumnName("AccountID");
            entity.Property(e => e.BatteryId)
                .HasMaxLength(50)
                .HasColumnName("BatteryID");
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .HasColumnName("description");
            entity.Property(e => e.Image)
                .HasMaxLength(50)
                .HasColumnName("image");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.StationId)
                .HasMaxLength(50)
                .HasColumnName("StationID");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");

            entity.HasOne(d => d.Account).WithMany(p => p.BatteryReports)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__BatteryRe__Accou__5BE2A6F2");

            entity.HasOne(d => d.Battery).WithMany(p => p.BatteryReports)
                .HasForeignKey(d => d.BatteryId)
                .HasConstraintName("FK__BatteryRe__Batte__5CD6CB2B");

            entity.HasOne(d => d.Station).WithMany(p => p.BatteryReports)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK__BatteryRe__Stati__5DCAEF64");
        });

        modelBuilder.Entity<BssStaff>(entity =>
        {
            entity.HasKey(e => e.StaffId).HasName("PK__BSS_Staf__96D4AAF7B9641C96");

            entity.ToTable("BSS_Staff");

            entity.Property(e => e.StaffId)
                .HasMaxLength(50)
                .HasColumnName("StaffID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(50)
                .HasColumnName("AccountID");
            entity.Property(e => e.StationId)
                .HasMaxLength(50)
                .HasColumnName("StationID");

            entity.HasOne(d => d.Account).WithMany(p => p.BssStaffs)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__BSS_Staff__Accou__5EBF139D");

            entity.HasOne(d => d.Station).WithMany(p => p.BssStaffs)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK__BSS_Staff__Stati__5FB337D6");
        });

        modelBuilder.Entity<Evdriver>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__EVDriver__A4AE64B84FF7B738");

            entity.ToTable("EVDriver");

            entity.Property(e => e.CustomerId)
                .HasMaxLength(50)
                .HasColumnName("CustomerID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(50)
                .HasColumnName("accountID");
            entity.Property(e => e.Vin)
                .HasMaxLength(25)
                .HasColumnName("VIN");

            entity.HasOne(d => d.Account).WithMany(p => p.Evdrivers)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__EVDriver__accoun__60A75C0F");

            entity.HasOne(d => d.VinNavigation).WithMany(p => p.Evdrivers)
                .HasForeignKey(d => d.Vin)
                .HasConstraintName("FK__EVDriver__VIN__619B8048");
        });

        modelBuilder.Entity<ExchangeBattery>(entity =>
        {
            entity.HasKey(e => e.ExchangeBatteryId).HasName("PK__Exchange__B321FE92975878A6");

            entity.ToTable("ExchangeBattery");

            entity.Property(e => e.ExchangeBatteryId)
                .HasMaxLength(50)
                .HasColumnName("ExchangeBatteryID");
            entity.Property(e => e.NewBatteryId)
                .HasMaxLength(50)
                .HasColumnName("NewBatteryID");
            entity.Property(e => e.Notes).HasMaxLength(50);
            entity.Property(e => e.OldBatteryId)
                .HasMaxLength(50)
                .HasColumnName("OldBatteryID");
            entity.Property(e => e.OrderId)
                .HasMaxLength(50)
                .HasColumnName("OrderID");
            entity.Property(e => e.ScheduleId)
                .HasMaxLength(50)
                .HasColumnName("ScheduleID");
            entity.Property(e => e.StaffAccountId)
                .HasMaxLength(50)
                .HasColumnName("StaffAccountID");
            entity.Property(e => e.StationId)
                .HasMaxLength(50)
                .HasColumnName("stationID");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.Vin)
                .HasMaxLength(25)
                .HasColumnName("VIN");

            entity.HasOne(d => d.NewBattery).WithMany(p => p.ExchangeBatteryNewBatteries)
                .HasForeignKey(d => d.NewBatteryId)
                .HasConstraintName("FK__ExchangeB__NewBa__628FA481");

            entity.HasOne(d => d.OldBattery).WithMany(p => p.ExchangeBatteryOldBatteries)
                .HasForeignKey(d => d.OldBatteryId)
                .HasConstraintName("FK__ExchangeB__OldBa__6383C8BA");

            entity.HasOne(d => d.Order).WithMany(p => p.ExchangeBatteries)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__ExchangeB__Order__6477ECF3");

            entity.HasOne(d => d.Schedule).WithMany(p => p.ExchangeBatteries)
                .HasForeignKey(d => d.ScheduleId)
                .HasConstraintName("FK__ExchangeB__Sched__656C112C");

            entity.HasOne(d => d.StaffAccount).WithMany(p => p.ExchangeBatteries)
                .HasForeignKey(d => d.StaffAccountId)
                .HasConstraintName("FK__ExchangeB__Staff__66603565");

            entity.HasOne(d => d.Station).WithMany(p => p.ExchangeBatteries)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK__ExchangeB__stati__6754599E");

            entity.HasOne(d => d.VinNavigation).WithMany(p => p.ExchangeBatteries)
                .HasForeignKey(d => d.Vin)
                .HasConstraintName("FK__ExchangeBat__VIN__68487DD7");
        });

        modelBuilder.Entity<Form>(entity =>
        {
            entity.HasKey(e => e.FormId).HasName("PK__Form__FB05B7BDB4D27DDE");

            entity.ToTable("Form");

            entity.Property(e => e.FormId)
                .HasMaxLength(50)
                .HasColumnName("FormID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(50)
                .HasColumnName("AccountID");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .HasColumnName("description");
            entity.Property(e => e.StationId)
                .HasMaxLength(50)
                .HasColumnName("StationID");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .HasMaxLength(50)
                .HasColumnName("title");

            entity.HasOne(d => d.Account).WithMany(p => p.Forms)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__Form__AccountID__693CA210");

            entity.HasOne(d => d.Station).WithMany(p => p.Forms)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK__Form__StationID__6A30C649");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BAF0859F60A");

            entity.Property(e => e.OrderId)
                .HasMaxLength(50)
                .HasColumnName("OrderID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(50)
                .HasColumnName("AccountID");
            entity.Property(e => e.BatteryId)
                .HasMaxLength(50)
                .HasColumnName("BatteryID");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.ServiceId)
                .HasMaxLength(50)
                .HasColumnName("ServiceID");

            entity.HasOne(d => d.Account).WithMany(p => p.Orders)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__Orders__AccountI__6B24EA82");

            entity.HasOne(d => d.Battery).WithMany(p => p.Orders)
                .HasForeignKey(d => d.BatteryId)
                .HasConstraintName("FK__Orders__BatteryI__6C190EBB");
        });

        modelBuilder.Entity<Package>(entity =>
        {
            entity.HasKey(e => e.PackageId).HasName("PK__Package__322035ECE405B783");

            entity.ToTable("Package");

            entity.Property(e => e.PackageId)
                .HasMaxLength(50)
                .HasColumnName("PackageID");
            entity.Property(e => e.BatteryId)
                .HasMaxLength(50)
                .HasColumnName("BatteryID");
            entity.Property(e => e.Description)
                .HasMaxLength(90)
                .HasColumnName("description");

            entity.HasOne(d => d.Battery).WithMany(p => p.Packages)
                .HasForeignKey(d => d.BatteryId)
                .HasConstraintName("FK__Package__Battery__6D0D32F4");
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.RatingId).HasName("PK__Rating__FCCDF85CC456E2FF");

            entity.ToTable("Rating");

            entity.Property(e => e.RatingId)
                .HasMaxLength(50)
                .HasColumnName("RatingID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(50)
                .HasColumnName("AccountID");
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .HasColumnName("description");
            entity.Property(e => e.Rating1)
                .HasMaxLength(50)
                .HasColumnName("rating");
            entity.Property(e => e.StationId)
                .HasMaxLength(50)
                .HasColumnName("StationID");

            entity.HasOne(d => d.Account).WithMany(p => p.Ratings)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__Rating__AccountI__6E01572D");

            entity.HasOne(d => d.Station).WithMany(p => p.Ratings)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK__Rating__StationI__6EF57B66");
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__Report__D5BD48E59BF960C8");

            entity.ToTable("Report");

            entity.Property(e => e.ReportId)
                .HasMaxLength(50)
                .HasColumnName("ReportID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(50)
                .HasColumnName("AccountID");
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .HasColumnName("description");
            entity.Property(e => e.Image)
                .HasMaxLength(50)
                .HasColumnName("image");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.StationId)
                .HasMaxLength(50)
                .HasColumnName("StationID");

            entity.HasOne(d => d.Account).WithMany(p => p.Reports)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__Report__AccountI__6FE99F9F");

            entity.HasOne(d => d.Station).WithMany(p => p.Reports)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK__Report__StationI__70DDC3D8");
        });

        modelBuilder.Entity<Slot>(entity =>
        {
            entity.HasKey(e => e.SlotId).HasName("PK__Slot__0A124A4F24BE4FFE");

            entity.ToTable("Slot");

            entity.Property(e => e.SlotId)
                .HasMaxLength(50)
                .HasColumnName("SlotID");
            entity.Property(e => e.BatteryId)
                .HasMaxLength(50)
                .HasColumnName("BatteryID");
            entity.Property(e => e.CordinateX).HasColumnName("cordinate_x");
            entity.Property(e => e.CordinateY).HasColumnName("cordinate_y");
            entity.Property(e => e.StationId)
                .HasMaxLength(50)
                .HasColumnName("StationID");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");

            entity.HasOne(d => d.Battery).WithMany(p => p.Slots)
                .HasForeignKey(d => d.BatteryId)
                .HasConstraintName("FK__Slot__BatteryID__71D1E811");

            entity.HasOne(d => d.Station).WithMany(p => p.Slots)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK__Slot__StationID__72C60C4A");
        });

        modelBuilder.Entity<Station>(entity =>
        {
            entity.HasKey(e => e.StationId).HasName("PK__Station__F0A7F3E055DEB6F6");

            entity.ToTable("Station");

            entity.Property(e => e.StationId)
                .HasMaxLength(50)
                .HasColumnName("stationID");
            entity.Property(e => e.BatteryNumber).HasColumnName("battery_number");
            entity.Property(e => e.Location)
                .HasMaxLength(50)
                .HasColumnName("location");
            entity.Property(e => e.Rating)
                .HasMaxLength(50)
                .HasColumnName("rating");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
        });

        modelBuilder.Entity<StationSchedule>(entity =>
        {
            entity.HasKey(e => e.StationScheduleId).HasName("PK__StationS__12BF61BE76FEF6F7");

            entity.ToTable("StationSchedule");

            entity.Property(e => e.StationScheduleId)
                .HasMaxLength(50)
                .HasColumnName("StationScheduleID");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .HasColumnName("description");
            entity.Property(e => e.FormId)
                .HasMaxLength(50)
                .HasColumnName("FormID");
            entity.Property(e => e.StationId)
                .HasMaxLength(50)
                .HasColumnName("StationID");

            entity.HasOne(d => d.Form).WithMany(p => p.StationSchedules)
                .HasForeignKey(d => d.FormId)
                .HasConstraintName("FK__StationSc__FormI__73BA3083");

            entity.HasOne(d => d.Station).WithMany(p => p.StationSchedules)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK__StationSc__Stati__74AE54BC");
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.Vin).HasName("PK__Vehicle__C5DF234DDE1772F5");

            entity.ToTable("Vehicle");

            entity.Property(e => e.Vin)
                .HasMaxLength(25)
                .HasColumnName("VIN");
            entity.Property(e => e.BatteryId)
                .HasMaxLength(50)
                .HasColumnName("BatteryID");
            entity.Property(e => e.PackageId)
                .HasMaxLength(50)
                .HasColumnName("PackageID");
            entity.Property(e => e.VehicleName)
                .HasMaxLength(50)
                .HasDefaultValueSql("(NULL)")
                .HasColumnName("vehicle_name");
            entity.Property(e => e.VehicleType)
                .HasMaxLength(50)
                .HasDefaultValueSql("(NULL)")
                .HasColumnName("vehicle_type");

            entity.HasOne(d => d.Battery).WithMany(p => p.Vehicles)
                .HasForeignKey(d => d.BatteryId)
                .HasConstraintName("FK__Vehicle__Battery__75A278F5");

            entity.HasOne(d => d.Package).WithMany(p => p.Vehicles)
                .HasForeignKey(d => d.PackageId)
                .HasConstraintName("FK__Vehicle__Package__76969D2E");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}