// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Vehicle
{
    public string Vin { get; set; }

    public string VehicleName { get; set; }

    public string VehicleType { get; set; }

    public string BatteryId { get; set; }

    public string PackageId { get; set; }

    public virtual Battery Battery { get; set; }

    public virtual ICollection<BatteryHistory> BatteryHistories { get; set; } = new List<BatteryHistory>();

    public virtual ICollection<Evdriver> Evdrivers { get; set; } = new List<Evdriver>();

    public virtual ICollection<ExchangeBattery> ExchangeBatteries { get; set; } = new List<ExchangeBattery>();

    public virtual Package Package { get; set; }
}