// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BusinessObjects.Models;

public partial class Vehicle
{
    public string Vin { get; set; }

    public string VehicleName { get; set; }

    public string VehicleType { get; set; }

    public string BatteryId { get; set; }

    public string PackageId { get; set; }

    public string Status { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string CustomerId { get; set; }

    public DateTime? PackageExpiredate { get; set; }
    [JsonIgnore]
    public virtual Battery Battery { get; set; }

    public virtual ICollection<BatteryHistory> BatteryHistories { get; set; } = new List<BatteryHistory>();
    [JsonIgnore]
    public virtual Evdriver Customer { get; set; }

    public virtual ICollection<ExchangeBattery> ExchangeBatteries { get; set; } = new List<ExchangeBattery>();
    [JsonIgnore]
    public virtual Package Package { get; set; }
}